services:
  - type: web
    name: fractureai
    runtime: python
    plan: free
    pythonVersion: "3.11.9"
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn fracture_ai.wsgi:application --workers 1 --timeout 120 --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: fracture_ai.settings_prod
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"
